# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.3      5.5      2.4    TBD
# SIMP 6.4      5.5      2.4    TBD
# PE 2018.1     5.5      2.4    2020-05 (LTS)
# PE 2019.1     6.4      2.5    2019-02-28
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
---
language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script:
  - bundle exec rake test
notifications:
  email: false
rvm:
  - 2.4.5
env:
  global:
    - STRICT_VARIABLES=yes
  matrix:
    - PUPPET_VERSION="~> 5.5.0"
    # --------------------------- non-critical versions
    - PUPPET_VERSION="~> 6.0"
matrix:
  fast_finish: true
  allow_failures:
    - env: PUPPET_VERSION="~> 6.0"
