# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.4      5.5      2.4    TBD
# PE 2018.1     5.5      2.4    2020-11 (LTS)
# PE 2019.2     6.10     2.5    2019-08 (STS)
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
---
language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update
  - bundle exec rake clean
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
addons:
  apt:
    packages:
      - rpm
notifications:
  email: false

stages:
  - test

jobs:
  include:
    - stage: test
      name: 'Puppet 5.5 (SIMP 6.4, PE 2018.1)'
      rvm: 2.4.5
      env: 'PUPPET_VERSION="~> 5.5.0"'
      script:
        - bundle exec rake test
    - stage: test
      name: 'Puppet 6.10 (PE 2019.2)'
      rvm: 2.5.7
      env: 'PUPPET_VERSION="~>6.10.0"'
      script:
        - bundle exec rake test

matrix:
  fast_finish: true
