name: Skeleton PR Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:

env:
  PDK_DISABLE_ANALYTICS: yes
  BUNDLE_WITHOUT: 'development:system_tests'

jobs:
  tests:
    name: 'Test Skeleton'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet:
          - label: 'Puppet 5.5 [SIMP 6.4/PE 2018.1]'
            puppet_version: '~> 5.5.22'
            ruby_version: '2.4'
            build_command: bundle exec puppet module build
          - label: 'Puppet 6.18 [SIMP 6.5/PE 2019.8]'
            puppet_version: '~> 6.18.0'
            ruby_version: '2.5'
            build_command: bundle exec rake build:pdk
          - label: 'Puppet 7.x'
            puppet_version: '~> 7.0'
            ruby_version: '2.7'
            build_command: bundle exec rake build:pdk
    env:
      PUPMOD_ANSWERS: "0.1.3\nsimp\nApache-2.0\nA simple dnsmasq module designed to test the module skeleton.\n https://github.com/simp/pupmod-simp-dnsmasq\n\n\n\n\n"
      BUILD_COMMAND: '${{matrix.puppet.build_command}}'
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Ruby for Puppet 5.5'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - name: Generate test module
        run: |
          printf "$PUPMOD_ANSWERS" > pupmod.answers
          bundle
          bundle exec rake generate[simp-dnsmasq] < pupmod.answers
      - run: rm -f Gemfile.lock
      - name: 'Install Ruby ${{matrix.puppet.ruby_version}} for build'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
          bundler-cache: false
        env:
          PUPPET_VERSION: '${{matrix.puppet.puppet_version}}'
          BUNDLE_PATH: ${{ github.workspace }}/.vendor/bundle--build
      - name: Build test module
        env:
          PUPPET_VERSION: '${{matrix.puppet.puppet_version}}'
          BUNDLE_PATH: ${{ github.workspace }}/.vendor/bundle--build
        run:  |
          cd dnsmasq
          bundle
          $BUILD_COMMAND
      - name: "Install Ruby ${{matrix.puppet.ruby_version}} using test module's Gemfile"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
          bundler-cache: false
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/dnsmasq/Gemfile
          BUNDLE_PATH: ${{ github.workspace }}/dnsmasq/.vendor/bundle--test
          PUPPET_VERSION: '${{matrix.puppet.puppet_version}}'
      - name: Run tests
        run: |
          cd dnsmasq
          bundle
          bundle exec rake check:dot_underscore
          bundle exec rake check:test_file
          bundle exec rake pkg:check_version
          bundle exec rake metadata_lint
          bundle exec rake pkg:compare_latest_tag
          bundle exec rake pkg:create_tag_changelog
          bundle exec rake lint
          bundle exec rake validate
          bundle exec rake test
        env:
          BUNDLE_PATH: ${{github.workspace}}/dnsmasq/.vendor/bundle--test
          BUNDLE_GEMFILE: ${{ github.workspace }}/dnsmasq/Gemfile
          PUPPET_VERSION: '${{matrix.puppet.puppet_version}}'
